// <copyright file="FieldsContent.cs" company="APIMatic">
// SeltzApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;

namespace SeltzApi.Standard.Models.Containers
{
    /// <summary>
    /// This is a container class for one-of types.
    /// </summary>
    [JsonConverter(
        typeof(UnionTypeConverter<FieldsContent>),
        new[] {
            typeof(BooleanCase),
            typeof(ContentOptionsCase)
        },
        true
    )]
    public abstract class FieldsContent
    {
        /// <summary>
        /// This is Boolean case.
        /// </summary>
        /// <returns>
        /// The FieldsContent instance, wrapping the provided bool value.
        /// </returns>
        public static FieldsContent FromBoolean(bool boolean)
        {
            return new BooleanCase().Set(boolean);
        }

        /// <summary>
        /// This is ContentOptions case.
        /// </summary>
        /// <returns>
        /// The FieldsContent instance, wrapping the provided ContentOptions value.
        /// </returns>
        public static FieldsContent FromContentOptions(ContentOptions contentOptions)
        {
            return new ContentOptionsCase().Set(contentOptions);
        }

        /// <summary>
        /// Method to match from the provided one-of cases. Here parameters
        /// represents the callback functions for one-of type cases. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public abstract T Match<T>(Func<bool, T> boolean, Func<ContentOptions, T> contentOptions);

        /// <summary>
        /// Method to match from the provided one-of cases. The parameters represent
        /// optional callback functions for one-of type cases. You may provide only
        /// the callbacks you are interested in; others can be left as <c>null</c>. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function, or the default value if no callback is provided for the matched case.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public T MatchSome<T>(Func<bool, T> boolean = null, Func<ContentOptions, T> contentOptions = null) =>
                Match(boolean, contentOptions);

        [JsonConverter(typeof(UnionTypeCaseConverter<BooleanCase, bool>), JTokenType.Boolean)]
        private sealed class BooleanCase : FieldsContent, ICaseValue<BooleanCase, bool>
        {
            public bool Value;

            public override T Match<T>(Func<bool, T> boolean, Func<ContentOptions, T> contentOptions) =>
                   boolean != null ? boolean(Value) : default;

            public BooleanCase Set(bool value)
            {
                Value = value;
                return this;
            }

            public bool Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<ContentOptionsCase, ContentOptions>))]
        private sealed class ContentOptionsCase : FieldsContent, ICaseValue<ContentOptionsCase, ContentOptions>
        {
            public ContentOptions Value;

            public override T Match<T>(Func<bool, T> boolean, Func<ContentOptions, T> contentOptions) =>
                   contentOptions != null ? contentOptions(Value) : default;

            public ContentOptionsCase Set(ContentOptions value)
            {
                Value = value;
                return this;
            }

            public ContentOptions Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }
    }
}