// <copyright file="FieldsSnippets.cs" company="APIMatic">
// SeltzApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;

namespace SeltzApi.Standard.Models.Containers
{
    /// <summary>
    /// This is a container class for one-of types.
    /// </summary>
    [JsonConverter(
        typeof(UnionTypeConverter<FieldsSnippets>),
        new[] {
            typeof(BooleanCase),
            typeof(SnippetOptionsCase)
        },
        true
    )]
    public abstract class FieldsSnippets
    {
        /// <summary>
        /// This is Boolean case.
        /// </summary>
        /// <returns>
        /// The FieldsSnippets instance, wrapping the provided bool value.
        /// </returns>
        public static FieldsSnippets FromBoolean(bool boolean)
        {
            return new BooleanCase().Set(boolean);
        }

        /// <summary>
        /// This is SnippetOptions case.
        /// </summary>
        /// <returns>
        /// The FieldsSnippets instance, wrapping the provided SnippetOptions value.
        /// </returns>
        public static FieldsSnippets FromSnippetOptions(SnippetOptions snippetOptions)
        {
            return new SnippetOptionsCase().Set(snippetOptions);
        }

        /// <summary>
        /// Method to match from the provided one-of cases. Here parameters
        /// represents the callback functions for one-of type cases. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public abstract T Match<T>(Func<bool, T> boolean, Func<SnippetOptions, T> snippetOptions);

        /// <summary>
        /// Method to match from the provided one-of cases. The parameters represent
        /// optional callback functions for one-of type cases. You may provide only
        /// the callbacks you are interested in; others can be left as <c>null</c>. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function, or the default value if no callback is provided for the matched case.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public T MatchSome<T>(Func<bool, T> boolean = null, Func<SnippetOptions, T> snippetOptions = null) =>
                Match(boolean, snippetOptions);

        [JsonConverter(typeof(UnionTypeCaseConverter<BooleanCase, bool>), JTokenType.Boolean)]
        private sealed class BooleanCase : FieldsSnippets, ICaseValue<BooleanCase, bool>
        {
            public bool Value;

            public override T Match<T>(Func<bool, T> boolean, Func<SnippetOptions, T> snippetOptions) =>
                   boolean != null ? boolean(Value) : default;

            public BooleanCase Set(bool value)
            {
                Value = value;
                return this;
            }

            public bool Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<SnippetOptionsCase, SnippetOptions>))]
        private sealed class SnippetOptionsCase : FieldsSnippets, ICaseValue<SnippetOptionsCase, SnippetOptions>
        {
            public SnippetOptions Value;

            public override T Match<T>(Func<bool, T> boolean, Func<SnippetOptions, T> snippetOptions) =>
                   snippetOptions != null ? snippetOptions(Value) : default;

            public SnippetOptionsCase Set(SnippetOptions value)
            {
                Value = value;
                return this;
            }

            public SnippetOptions Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }
    }
}