// <copyright file="SeltzApiClient.cs" company="APIMatic">
// SeltzApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Authentication;
using APIMatic.Core.Utilities;
using APIMatic.Core.Utilities.Logger.Configuration;
using Microsoft.Extensions.Configuration;
using SeltzApi.Standard.Apis;
using SeltzApi.Standard.Authentication;
using SeltzApi.Standard.Http.Client;
using SeltzApi.Standard.Logging;
using System;
using System.Collections.Generic;

namespace SeltzApi.Standard
{
    /// <summary>
    /// The gateway for the SDK. This class acts as a factory for Api and holds the
    /// configuration of the SDK.
    /// </summary>
    public sealed class SeltzApiClient : IConfiguration
    {
        // A map of environments and their corresponding servers/baseurls
        private static readonly Dictionary<Environment, Dictionary<Enum, string>> EnvironmentsMap =
            new Dictionary<Environment, Dictionary<Enum, string>>
        {
            {
                Environment.Production, new Dictionary<Enum, string>
                {
                    { Server.Default, "https://api.seltz.ai" },
                }
            },
        };

        private readonly GlobalConfiguration globalConfiguration;
        private SdkLoggingConfiguration sdkLoggingConfiguration;
        private const string userAgent = "DotNet-SDK/0.0.2 (OS: {os-info}, Engine: {engine}/{engine-version})";
        private readonly HttpCallback httpCallback;
        private readonly Lazy<SearchApi> search;
        private readonly Lazy<AnswerApi> answer;
        private readonly Lazy<MonitorsApi> monitors;
        private readonly Lazy<RecordsApi> records;
        private readonly Lazy<RunsApi> runs;
        private readonly Lazy<AgentApi> agent;
        private readonly Lazy<FetchApi> fetch;

        private SeltzApiClient(
            Environment environment,
            CustomHeaderAuthenticationModel customHeaderAuthenticationModel,
            HttpCallback httpCallback,
            IHttpClientConfiguration httpClientConfiguration,
            SdkLoggingConfiguration sdkLoggingConfiguration)
        {
            this.Environment = environment;
            this.httpCallback = httpCallback;
            this.HttpClientConfiguration = httpClientConfiguration;
            this.sdkLoggingConfiguration = sdkLoggingConfiguration;
            CustomHeaderAuthenticationModel = customHeaderAuthenticationModel;
            var customHeaderAuthenticationManager = new CustomHeaderAuthenticationManager(customHeaderAuthenticationModel);
            globalConfiguration = new GlobalConfiguration.Builder()
                .AuthManagers(new Dictionary<string, AuthManager> {
                    {"ApiKeyAuth", customHeaderAuthenticationManager},
                })
                .ApiCallback(httpCallback)
                .HttpConfiguration(httpClientConfiguration)
                .ServerUrls(EnvironmentsMap[environment], Server.Default)
                .LoggingConfig(sdkLoggingConfiguration)
                .UserAgent(userAgent)
                .Build();
            CustomHeaderAuthenticationCredentials = customHeaderAuthenticationManager;

            this.search = new Lazy<SearchApi>(
                () => new SearchApi(globalConfiguration));
            this.answer = new Lazy<AnswerApi>(
                () => new AnswerApi(globalConfiguration));
            this.monitors = new Lazy<MonitorsApi>(
                () => new MonitorsApi(globalConfiguration));
            this.records = new Lazy<RecordsApi>(
                () => new RecordsApi(globalConfiguration));
            this.runs = new Lazy<RunsApi>(
                () => new RunsApi(globalConfiguration));
            this.agent = new Lazy<AgentApi>(
                () => new AgentApi(globalConfiguration));
            this.fetch = new Lazy<FetchApi>(
                () => new FetchApi(globalConfiguration));
        }

        /// <summary>
        /// Gets SearchApi.
        /// </summary>
        public SearchApi SearchApi => this.search.Value;

        /// <summary>
        /// Gets AnswerApi.
        /// </summary>
        public AnswerApi AnswerApi => this.answer.Value;

        /// <summary>
        /// Gets MonitorsApi.
        /// </summary>
        public MonitorsApi MonitorsApi => this.monitors.Value;

        /// <summary>
        /// Gets RecordsApi.
        /// </summary>
        public RecordsApi RecordsApi => this.records.Value;

        /// <summary>
        /// Gets RunsApi.
        /// </summary>
        public RunsApi RunsApi => this.runs.Value;

        /// <summary>
        /// Gets AgentApi.
        /// </summary>
        public AgentApi AgentApi => this.agent.Value;

        /// <summary>
        /// Gets FetchApi.
        /// </summary>
        public FetchApi FetchApi => this.fetch.Value;

        /// <summary>
        /// Gets the configuration of the Http Client associated with this client.
        /// </summary>
        public IHttpClientConfiguration HttpClientConfiguration { get; }

        /// <summary>
        /// Gets Environment.
        /// Current API environment.
        /// </summary>
        public Environment Environment { get; }

        /// <summary>
        /// Gets http callback.
        /// </summary>
        public HttpCallback HttpCallback => this.httpCallback;

        /// <summary>
        /// Gets the credentials to use with CustomHeaderAuthentication.
        /// </summary>
        public ICustomHeaderAuthenticationCredentials CustomHeaderAuthenticationCredentials { get; private set; }

        /// <summary>
        /// Gets the credentials model to use with CustomHeaderAuthentication.
        /// </summary>
        public CustomHeaderAuthenticationModel CustomHeaderAuthenticationModel { get; private set; }

        /// <summary>
        /// Gets the URL for a particular alias in the current environment and appends
        /// it with template parameters.
        /// </summary>
        /// <param name="alias">Default value:DEFAULT.</param>
        /// <returns>Returns the baseurl.</returns>
        public string GetBaseUri(Server alias = Server.Default)
        {
            return globalConfiguration.ServerUrl(alias);
        }

        /// <summary>
        /// Creates an object of the SeltzApiClient using the values provided for the builder.
        /// </summary>
        /// <returns>Builder.</returns>
        public Builder ToBuilder()
        {
            Builder builder = new Builder()
                .Environment(this.Environment)
                .HttpCallback(httpCallback)
                .LoggingConfig(sdkLoggingConfiguration)
                .HttpClientConfig(config => config.Build());

            if (CustomHeaderAuthenticationModel != null)
            {
                builder.CustomHeaderAuthenticationCredentials(CustomHeaderAuthenticationModel.ToBuilder().Build());
            }

            return builder;
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            return
                $"Environment = {this.Environment}, " +
                $"HttpClientConfiguration = {this.HttpClientConfiguration}, ";
        }

        /// <summary>
        /// Creates the client using builder.
        /// </summary>
        /// <returns> SeltzApiClient.</returns>
        internal static SeltzApiClient CreateFromEnvironment()
        {
            var builder = new Builder();

            string environment = System.Environment.GetEnvironmentVariable("SELTZ_API_STANDARD_ENVIRONMENT");
            string xApiKey = System.Environment.GetEnvironmentVariable("SELTZ_API_STANDARD_X_API_KEY");

            if (environment != null)
            {
                builder.Environment(CoreHelper.JsonDeserialize<Environment>($"\"{environment}\""));
            }

            if (xApiKey != null)
            {
                builder.CustomHeaderAuthenticationCredentials(new CustomHeaderAuthenticationModel
                .Builder(xApiKey)
                .Build());
            }

            return builder.Build();
        }

        /// <summary>
        /// Creates the client from configuration.
        /// </summary>
        /// <returns> SeltzApiClient.</returns>
        public static SeltzApiClient FromConfiguration(IConfigurationSection configuration) =>
            Builder.FromConfiguration(configuration).Build();

        /// <summary>
        /// Builder class.
        /// </summary>
        public class Builder
        {
            private Environment _environment = SeltzApi.Standard.Environment.Production;
            private CustomHeaderAuthenticationModel _customHeaderAuthenticationModel = new CustomHeaderAuthenticationModel();
            private HttpClientConfiguration.Builder _httpClientConfig = new HttpClientConfiguration.Builder();
            private HttpCallback _httpCallback;
            private SdkLoggingConfiguration _sdkLoggingConfiguration;

            /// <summary>
            /// Sets credentials for CustomHeaderAuthentication.
            /// </summary>
            /// <param name="customHeaderAuthenticationModel">CustomHeaderAuthenticationModel.</param>
            /// <returns>Builder.</returns>
            public Builder CustomHeaderAuthenticationCredentials(CustomHeaderAuthenticationModel customHeaderAuthenticationModel)
            {
                _customHeaderAuthenticationModel = customHeaderAuthenticationModel ??
                    throw new ArgumentNullException(nameof(customHeaderAuthenticationModel));
                return this;
            }

            /// <summary>
            /// Sets Environment.
            /// </summary>
            /// <param name="environment"> Environment. </param>
            /// <returns> Builder. </returns>
            public Builder Environment(Environment environment)
            {
                _environment = environment;
                return this;
            }

            /// <summary>
            /// Sets HttpClientConfig.
            /// </summary>
            /// <param name="action"> Action. </param>
            /// <returns>Builder.</returns>
            public Builder HttpClientConfig(Action<HttpClientConfiguration.Builder> action)
            {
                if (action is null)
                {
                    throw new ArgumentNullException(nameof(action));
                }

                action(_httpClientConfig);
                return this;
            }

            private Builder HttpClientConfig(HttpClientConfiguration.Builder httpClientConfigurationBuilder)
            {
                if (httpClientConfigurationBuilder != null)
                {
                    _httpClientConfig = httpClientConfigurationBuilder;
                }

                return this;
            }

            /// <summary>
            /// Sets the default logging configuration, using the Console logger.
            /// </summary>
            /// <returns>Builder.</returns>
            public Builder LoggingConfig()
            {
                _sdkLoggingConfiguration = SdkLoggingConfiguration.Console();
                return this;
            }

            /// <summary>
            /// Sets the logging configuration using the provided <paramref name="action"/>.
            /// </summary>
            /// <param name="action">The action to perform on the logging configuration builder.</param>
            /// <returns>Builder.</returns>
            /// <exception cref="ArgumentNullException">Thrown when <paramref name="action"/> is null.</exception>
            public Builder LoggingConfig(Action<LogBuilder> action)
            {
                if (action is null) throw new ArgumentNullException(nameof(action));
                var logBuilder =
                    LogBuilder.CreateFromConfig(_sdkLoggingConfiguration ?? SdkLoggingConfiguration.Console());
                action(logBuilder);
                _sdkLoggingConfiguration = logBuilder.Build();
                return this;
            }

            internal Builder LoggingConfig(SdkLoggingConfiguration configuration)
            {
                _sdkLoggingConfiguration = configuration;
                return this;
            }

            /// <summary>
            /// Sets the HttpCallback for the Builder.
            /// </summary>
            /// <param name="httpCallback"> http callback. </param>
            /// <returns>Builder.</returns>
            public Builder HttpCallback(HttpCallback httpCallback)
            {
                _httpCallback = httpCallback;
                return this;
            }

            /// <summary>
            /// Creates an object of the SeltzApiClient using the values provided for the builder.
            /// </summary>
            /// <returns>SeltzApiClient.</returns>
            public SeltzApiClient Build()
            {
                if (_customHeaderAuthenticationModel.XApiKey == null)
                {
                    _customHeaderAuthenticationModel = null;
                }
                return new SeltzApiClient(
                    _environment,
                    _customHeaderAuthenticationModel,
                    _httpCallback,
                    _httpClientConfig.Build(),
                    _sdkLoggingConfiguration);
            }

            /// <summary>
            /// Creates the client builder from configuration.
            /// </summary>
            /// <returns> Builder.</returns>
            public static Builder FromConfiguration(IConfigurationSection config)
            {
                var builder = new Builder();
                var options = config.Get<SeltzApiClientOptions>();
                if (options == null) return builder;
                if (options.Environment != null)
                    builder.Environment(options.Environment.Value);
                if (options.CustomHeaderAuthenticationCredentials != null)
                    builder.CustomHeaderAuthenticationCredentials(CustomHeaderAuthenticationModel.FromOptions(options.CustomHeaderAuthenticationCredentials));
                if (options.HttpClientConfig != null)
                    builder.HttpClientConfig(Http.Client.HttpClientConfiguration.FromOptions(options.HttpClientConfig));
                if (options.LoggingConfig != null)
                    builder.LoggingConfig(LogBuilder.FromOptions(options.LoggingConfig));
                return builder;
            }
        }

        public class SeltzApiClientOptions
        {
            public Environment? Environment { get; set; }
            public CustomHeaderAuthenticationModelOptions CustomHeaderAuthenticationCredentials { get; set; }
            public HttpClientConfigurationOptions HttpClientConfig { get; set; }
            public LoggingConfigOptions LoggingConfig { get; set; }
        }
    }
}
