// <copyright file="CustomHeaderAuthenticationManager.cs" company="APIMatic">
// SeltzApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using APIMatic.Core.Authentication;

namespace SeltzApi.Standard.Authentication
{
    /// <summary>
    /// CustomHeaderAuthenticationManager Class.
    /// </summary>
    internal class CustomHeaderAuthenticationManager : AuthManager, ICustomHeaderAuthenticationCredentials
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CustomHeaderAuthenticationManager"/> class.
        /// </summary>
        /// <param name="customHeaderAuthenticationModel">CustomHeaderAuthenticationModel.</param>
        public CustomHeaderAuthenticationManager(CustomHeaderAuthenticationModel customHeaderAuthenticationModel)
        {
            XApiKey = customHeaderAuthenticationModel?.XApiKey;
            Parameters(paramBuilder => paramBuilder
                .Header(header => header.Setup("x-api-key", XApiKey).Required())
            );
        }

        /// <summary>
        /// Gets string value for xApiKey.
        /// </summary>
        public string XApiKey { get; }

        /// <summary>
        /// Check if credentials match.
        /// </summary>
        /// <param name="xApiKey"> The string value for credentials.</param>
        /// <returns> True if credentials matched.</returns>
        public bool Equals(string xApiKey)
        {
            return xApiKey.Equals(this.XApiKey);
        }
    }

    public sealed class CustomHeaderAuthenticationModel
    {
        internal CustomHeaderAuthenticationModel()
        {
        }

        internal string XApiKey { get; set; }

        /// <summary>
        /// Creates an object of the CustomHeaderAuthenticationModel using the values provided for the builder.
        /// </summary>
        /// <returns>Builder.</returns>
        public Builder ToBuilder()
        {
            return new Builder(XApiKey);
        }

        /// <summary>
        /// Builder class for CustomHeaderAuthenticationModel.
        /// </summary>
        public class Builder
        {
            private string xApiKey;

            public Builder(string xApiKey)
            {
                this.xApiKey = xApiKey ?? throw new ArgumentNullException(nameof(xApiKey));
            }

            /// <summary>
            /// Sets XApiKey.
            /// </summary>
            /// <param name="xApiKey">XApiKey.</param>
            /// <returns>Builder.</returns>
            public Builder XApiKey(string xApiKey)
            {
                this.xApiKey = xApiKey ?? throw new ArgumentNullException(nameof(xApiKey));
                return this;
            }

            /// <summary>
            /// Creates an object of the CustomHeaderAuthenticationModel using the values provided for the builder.
            /// </summary>
            /// <returns>CustomHeaderAuthenticationModel.</returns>
            public CustomHeaderAuthenticationModel Build()
            {
                return new CustomHeaderAuthenticationModel()
                {
                    XApiKey = this.xApiKey
                };
            }
        }

        internal static CustomHeaderAuthenticationModel FromOptions(CustomHeaderAuthenticationModelOptions options)
        {
            var builder = new Builder(options.XApiKey);
            return builder.Build();
        }
    }

    public class CustomHeaderAuthenticationModelOptions
    {
        public string XApiKey { get; set; }
    }
    
}