// <copyright file="ICustomHeaderAuthenticationCredentials.cs" company="APIMatic">
// SeltzApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>

namespace SeltzApi.Standard.Authentication
{
    /// <summary>
    /// Authentication configuration interface for CustomHeaderAuthentication.
    /// </summary>
    public interface ICustomHeaderAuthenticationCredentials
    {
        /// <summary>
        /// Gets string value for xApiKey.
        /// </summary>
        string XApiKey { get; }

        /// <summary>
        ///  Returns true if credentials matched.
        /// </summary>
        /// <param name="xApiKey"> The string value for credentials.</param>
        /// <returns>True if credentials matched.</returns>
        bool Equals(string xApiKey);
    }
}