// <copyright file="AgentRunStopReason2.cs" company="APIMatic">
// SeltzApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SeltzApi.Standard.Models
{
    /// <summary>
    /// AgentRunStopReason2.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum AgentRunStopReason2
    {
        /// <summary>
        /// Finished.
        /// </summary>
        [EnumMember(Value = "finished")]
        Finished,

        /// <summary>
        /// BudgetReached.
        /// </summary>
        [EnumMember(Value = "budget_reached")]
        BudgetReached,

        /// <summary>
        /// Timeout.
        /// </summary>
        [EnumMember(Value = "timeout")]
        Timeout,

        /// <summary>
        /// Cancelled.
        /// </summary>
        [EnumMember(Value = "cancelled")]
        Cancelled,

        /// <summary>
        /// InvalidOutput.
        /// </summary>
        [EnumMember(Value = "invalid_output")]
        InvalidOutput,

        /// <summary>
        /// InternalError.
        /// </summary>
        [EnumMember(Value = "internal_error")]
        InternalError
    }
}