// <copyright file="AgentRunRequest2.cs" company="APIMatic">
// SeltzApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SeltzApi.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SeltzApi.Standard.Models
{
    /// <summary>
    /// AgentRunRequest2.
    /// </summary>
    public class AgentRunRequest2
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private string effort;
        private object outputSchema;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "effort", false },
            { "output_schema", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="AgentRunRequest2"/> class.
        /// </summary>
        public AgentRunRequest2()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AgentRunRequest2"/> class.
        /// </summary>
        /// <param name="effort">effort.</param>
        /// <param name="outputSchema">output_schema.</param>
        /// <param name="query">query.</param>
        public AgentRunRequest2(
            string effort = null,
            object outputSchema = null,
            string query = "")
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();

            if (effort != null)
            {
                this.Effort = effort;
            }

            if (outputSchema != null)
            {
                this.OutputSchema = outputSchema;
            }
            this.Query = query;
        }

        /// <summary>
        /// The effort level the run executes at: the request's `effort`, or the
        /// default level when it named none.
        /// </summary>
        [JsonProperty("effort")]
        public string Effort
        {
            get
            {
                return this.effort;
            }

            set
            {
                this.shouldSerialize["effort"] = true;
                this.effort = value;
            }
        }

        /// <summary>
        /// The request's `output_schema`, when one was given. On gRPC the object is
        /// JSON-encoded.
        /// </summary>
        [JsonProperty("output_schema")]
        public object OutputSchema
        {
            get
            {
                return this.outputSchema;
            }

            set
            {
                this.shouldSerialize["output_schema"] = true;
                this.outputSchema = value;
            }
        }

        /// <summary>
        /// The natural-language question.
        /// </summary>
        [JsonProperty("query", NullValueHandling = NullValueHandling.Ignore)]
        public string Query { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"AgentRunRequest2 : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetEffort()
        {
            this.shouldSerialize["effort"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetOutputSchema()
        {
            this.shouldSerialize["output_schema"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeEffort()
        {
            return this.shouldSerialize["effort"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeOutputSchema()
        {
            return this.shouldSerialize["output_schema"];
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Effort = {this.Effort ?? "null"}");
            toStringOutput.Add($"OutputSchema = {(this.OutputSchema == null ? "null" : this.OutputSchema.ToString())}");
            toStringOutput.Add($"Query = {this.Query ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}