// <copyright file="AgentRunOutput2.cs" company="APIMatic">
// SeltzApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SeltzApi.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SeltzApi.Standard.Models
{
    /// <summary>
    /// AgentRunOutput2.
    /// </summary>
    public class AgentRunOutput2
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private object structured;
        private string text;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "structured", false },
            { "text", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="AgentRunOutput2"/> class.
        /// </summary>
        public AgentRunOutput2()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AgentRunOutput2"/> class.
        /// </summary>
        /// <param name="grounding">grounding.</param>
        /// <param name="sources">sources.</param>
        /// <param name="structured">structured.</param>
        /// <param name="text">text.</param>
        public AgentRunOutput2(
            List<Models.AgentRunGrounding> grounding = null,
            List<Models.AgentRunSource> sources = null,
            object structured = null,
            string text = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Grounding = grounding;
            this.Sources = sources;

            if (structured != null)
            {
                this.Structured = structured;
            }

            if (text != null)
            {
                this.Text = text;
            }
        }

        /// <summary>
        /// Per-field citations for `structured`. Empty when there is no structured
        /// output.
        /// </summary>
        [JsonProperty("grounding", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.AgentRunGrounding> Grounding { get; set; }

        /// <summary>
        /// The sources cited by `text` or `grounding`, numbered in order of first
        /// citation.
        /// </summary>
        [JsonProperty("sources", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.AgentRunSource> Sources { get; set; }

        /// <summary>
        /// Structured result shaped by the request's `output_schema`. Unset when the
        /// request had none. Fields that could not be grounded are expected to be
        /// null. On gRPC the object is JSON-encoded.
        /// </summary>
        [JsonProperty("structured")]
        public object Structured
        {
            get
            {
                return this.structured;
            }

            set
            {
                this.shouldSerialize["structured"] = true;
                this.structured = value;
            }
        }

        /// <summary>
        /// Cited markdown report. Inline `\[n\]` markers cite the entry of `sources`
        /// whose `id` is `n`.
        /// </summary>
        [JsonProperty("text")]
        public string Text
        {
            get
            {
                return this.text;
            }

            set
            {
                this.shouldSerialize["text"] = true;
                this.text = value;
            }
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"AgentRunOutput2 : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetStructured()
        {
            this.shouldSerialize["structured"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetText()
        {
            this.shouldSerialize["text"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeStructured()
        {
            return this.shouldSerialize["structured"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeText()
        {
            return this.shouldSerialize["text"];
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Grounding = {(this.Grounding == null ? "null" : $"[{string.Join(", ", this.Grounding)} ]")}");
            toStringOutput.Add($"Sources = {(this.Sources == null ? "null" : $"[{string.Join(", ", this.Sources)} ]")}");
            toStringOutput.Add($"Structured = {(this.Structured == null ? "null" : this.Structured.ToString())}");
            toStringOutput.Add($"Text = {this.Text ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}