// <copyright file="AgentRun.cs" company="APIMatic">
// SeltzApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SeltzApi.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SeltzApi.Standard.Models
{
    /// <summary>
    /// AgentRun.
    /// </summary>
    public class AgentRun
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private string completedAt;
        private Models.AgentRunOutput2 output;
        private Models.AgentRunRequest2 request;
        private string startedAt;
        private Models.AgentRunStopReason2? stopReason;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "completed_at", false },
            { "output", false },
            { "request", false },
            { "started_at", false },
            { "stop_reason", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="AgentRun"/> class.
        /// </summary>
        public AgentRun()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AgentRun"/> class.
        /// </summary>
        /// <param name="completedAt">completed_at.</param>
        /// <param name="createdAt">created_at.</param>
        /// <param name="id">id.</param>
        /// <param name="mObject">object.</param>
        /// <param name="output">output.</param>
        /// <param name="request">request.</param>
        /// <param name="startedAt">started_at.</param>
        /// <param name="status">status.</param>
        /// <param name="stopReason">stop_reason.</param>
        public AgentRun(
            string completedAt = null,
            string createdAt = "",
            string id = "",
            string mObject = "",
            Models.AgentRunOutput2 output = null,
            Models.AgentRunRequest2 request = null,
            string startedAt = null,
            Models.AgentRunStatus2? status = Models.AgentRunStatus2.Pending,
            Models.AgentRunStopReason2? stopReason = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();

            if (completedAt != null)
            {
                this.CompletedAt = completedAt;
            }
            this.CreatedAt = createdAt;
            this.Id = id;
            this.MObject = mObject;

            if (output != null)
            {
                this.Output = output;
            }

            if (request != null)
            {
                this.Request = request;
            }

            if (startedAt != null)
            {
                this.StartedAt = startedAt;
            }
            this.Status = status;

            if (stopReason != null)
            {
                this.StopReason = stopReason;
            }
        }

        /// <summary>
        /// When the run reached a terminal state. Unset until then.
        /// </summary>
        [JsonProperty("completed_at")]
        public string CompletedAt
        {
            get
            {
                return this.completedAt;
            }

            set
            {
                this.shouldSerialize["completed_at"] = true;
                this.completedAt = value;
            }
        }

        /// <summary>
        /// When the run was created, as an ISO 8601 timestamp.
        /// </summary>
        [JsonProperty("created_at", NullValueHandling = NullValueHandling.Ignore)]
        public string CreatedAt { get; set; }

        /// <summary>
        /// Unique run id.
        /// </summary>
        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public string Id { get; set; }

        /// <summary>
        /// Object type, always "agent.run".
        /// </summary>
        [JsonProperty("object", NullValueHandling = NullValueHandling.Ignore)]
        public string MObject { get; set; }

        /// <summary>
        /// Gets or sets Output.
        /// </summary>
        [JsonProperty("output")]
        public Models.AgentRunOutput2 Output
        {
            get
            {
                return this.output;
            }

            set
            {
                this.shouldSerialize["output"] = true;
                this.output = value;
            }
        }

        /// <summary>
        /// Gets or sets Request.
        /// </summary>
        [JsonProperty("request")]
        public Models.AgentRunRequest2 Request
        {
            get
            {
                return this.request;
            }

            set
            {
                this.shouldSerialize["request"] = true;
                this.request = value;
            }
        }

        /// <summary>
        /// When the run started. Unset while pending.
        /// </summary>
        [JsonProperty("started_at")]
        public string StartedAt
        {
            get
            {
                return this.startedAt;
            }

            set
            {
                this.shouldSerialize["started_at"] = true;
                this.startedAt = value;
            }
        }

        /// <summary>
        /// Gets or sets Status.
        /// </summary>
        [JsonProperty("status", NullValueHandling = NullValueHandling.Ignore)]
        public Models.AgentRunStatus2? Status { get; set; }

        /// <summary>
        /// Gets or sets StopReason.
        /// </summary>
        [JsonProperty("stop_reason")]
        public Models.AgentRunStopReason2? StopReason
        {
            get
            {
                return this.stopReason;
            }

            set
            {
                this.shouldSerialize["stop_reason"] = true;
                this.stopReason = value;
            }
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"AgentRun : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetCompletedAt()
        {
            this.shouldSerialize["completed_at"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetOutput()
        {
            this.shouldSerialize["output"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetRequest()
        {
            this.shouldSerialize["request"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetStartedAt()
        {
            this.shouldSerialize["started_at"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetStopReason()
        {
            this.shouldSerialize["stop_reason"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeCompletedAt()
        {
            return this.shouldSerialize["completed_at"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeOutput()
        {
            return this.shouldSerialize["output"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeRequest()
        {
            return this.shouldSerialize["request"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeStartedAt()
        {
            return this.shouldSerialize["started_at"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeStopReason()
        {
            return this.shouldSerialize["stop_reason"];
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"CompletedAt = {this.CompletedAt ?? "null"}");
            toStringOutput.Add($"CreatedAt = {this.CreatedAt ?? "null"}");
            toStringOutput.Add($"Id = {this.Id ?? "null"}");
            toStringOutput.Add($"MObject = {this.MObject ?? "null"}");
            toStringOutput.Add($"Output = {(this.Output == null ? "null" : this.Output.ToString())}");
            toStringOutput.Add($"Request = {(this.Request == null ? "null" : this.Request.ToString())}");
            toStringOutput.Add($"StartedAt = {this.StartedAt ?? "null"}");
            toStringOutput.Add($"Status = {(this.Status == null ? "null" : this.Status.ToString())}");
            toStringOutput.Add($"StopReason = {(this.StopReason == null ? "null" : this.StopReason.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}