// <copyright file="AnswerHttpRequest.cs" company="APIMatic">
// SeltzApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SeltzApi.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SeltzApi.Standard.Models
{
    /// <summary>
    /// AnswerHttpRequest.
    /// </summary>
    public class AnswerHttpRequest
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private string apiKey;
        private string model;
        private string scope;
        private string systemPrompt;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "api_key", false },
            { "model", false },
            { "scope", false },
            { "system_prompt", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="AnswerHttpRequest"/> class.
        /// </summary>
        public AnswerHttpRequest()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AnswerHttpRequest"/> class.
        /// </summary>
        /// <param name="query">query.</param>
        /// <param name="apiKey">api_key.</param>
        /// <param name="includeContent">include_content.</param>
        /// <param name="model">model.</param>
        /// <param name="responseFormat">response_format.</param>
        /// <param name="scope">scope.</param>
        /// <param name="stream">stream.</param>
        /// <param name="systemPrompt">system_prompt.</param>
        public AnswerHttpRequest(
            string query,
            string apiKey = null,
            bool? includeContent = null,
            string model = null,
            object responseFormat = null,
            string scope = null,
            bool? stream = null,
            string systemPrompt = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();

            if (apiKey != null)
            {
                this.ApiKey = apiKey;
            }
            this.IncludeContent = includeContent;

            if (model != null)
            {
                this.Model = model;
            }
            this.Query = query;
            this.ResponseFormat = responseFormat;

            if (scope != null)
            {
                this.Scope = scope;
            }
            this.Stream = stream;

            if (systemPrompt != null)
            {
                this.SystemPrompt = systemPrompt;
            }
        }

        /// <summary>
        /// API key. Either this or the `x-api-key` header must be supplied;
        /// the header takes precedence.
        /// </summary>
        [JsonProperty("api_key")]
        public string ApiKey
        {
            get
            {
                return this.apiKey;
            }

            set
            {
                this.shouldSerialize["api_key"] = true;
                this.apiKey = value;
            }
        }

        /// <summary>
        /// When true, citations carry the document content text. Default false.
        /// </summary>
        [JsonProperty("include_content", NullValueHandling = NullValueHandling.Ignore)]
        public bool? IncludeContent { get; set; }

        /// <summary>
        /// Selects the answer tier, which determines behavior and billing.
        /// Omitted resolves to the default tier. Independent of `scope`; the
        /// response shape is unchanged.
        /// </summary>
        [JsonProperty("model")]
        public string Model
        {
            get
            {
                return this.model;
            }

            set
            {
                this.shouldSerialize["model"] = true;
                this.model = value;
            }
        }

        /// <summary>
        /// The natural-language question.
        /// </summary>
        [JsonProperty("query")]
        public string Query { get; set; }

        /// <summary>
        /// Optional `OpenAI` `response_format` object (`{"type": "text" |
        /// "json_object" | "json_schema", ...}`), accepted as raw JSON exactly
        /// like `/v1/chat/completions`. Under a structured type no inline
        /// citations are added, so the answer stays schema-valid; a malformed
        /// value is a `400` before billing. Omitted leaves the answer as Markdown
        /// prose.
        /// Applies at every tier.
        /// </summary>
        [JsonProperty("response_format", NullValueHandling = NullValueHandling.Ignore)]
        public object ResponseFormat { get; set; }

        /// <summary>
        /// Restricts the grounding search to one scope.
        /// Currently available:
        /// - `news`
        /// - `wikipedia`
        /// - `people`
        /// - `companies`
        /// Omitted, empty or whitespace-only searches the default scope.
        /// </summary>
        [JsonProperty("scope")]
        public string Scope
        {
            get
            {
                return this.scope;
            }

            set
            {
                this.shouldSerialize["scope"] = true;
                this.scope = value;
            }
        }

        /// <summary>
        /// When true, stream the answer as OpenAI-mimic SSE chunks. Default false.
        /// </summary>
        [JsonProperty("stream", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Stream { get; set; }

        /// <summary>
        /// Steers how the answer is presented — tone, voice, format. It is
        /// subordinate to the grounding and citation rules, which stay in force.
        /// That precedence is instructional, not a sandbox. Omitted, empty or
        /// whitespace-only leaves the presentation unchanged. Applies at every
        /// tier and composes with `response_format`. At most 8 KiB of UTF-8; a
        /// longer value is a `400` before billing.
        /// </summary>
        [JsonProperty("system_prompt")]
        public string SystemPrompt
        {
            get
            {
                return this.systemPrompt;
            }

            set
            {
                this.shouldSerialize["system_prompt"] = true;
                this.systemPrompt = value;
            }
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"AnswerHttpRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetApiKey()
        {
            this.shouldSerialize["api_key"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetModel()
        {
            this.shouldSerialize["model"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetScope()
        {
            this.shouldSerialize["scope"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetSystemPrompt()
        {
            this.shouldSerialize["system_prompt"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeApiKey()
        {
            return this.shouldSerialize["api_key"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeModel()
        {
            return this.shouldSerialize["model"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeScope()
        {
            return this.shouldSerialize["scope"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeSystemPrompt()
        {
            return this.shouldSerialize["system_prompt"];
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"ApiKey = {this.ApiKey ?? "null"}");
            toStringOutput.Add($"IncludeContent = {(this.IncludeContent == null ? "null" : this.IncludeContent.ToString())}");
            toStringOutput.Add($"Model = {this.Model ?? "null"}");
            toStringOutput.Add($"Query = {this.Query ?? "null"}");
            toStringOutput.Add($"ResponseFormat = {(this.ResponseFormat == null ? "null" : this.ResponseFormat.ToString())}");
            toStringOutput.Add($"Scope = {this.Scope ?? "null"}");
            toStringOutput.Add($"Stream = {(this.Stream == null ? "null" : this.Stream.ToString())}");
            toStringOutput.Add($"SystemPrompt = {this.SystemPrompt ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}