// <copyright file="ContentOptions.cs" company="APIMatic">
// SeltzApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SeltzApi.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SeltzApi.Standard.Models
{
    /// <summary>
    /// ContentOptions.
    /// </summary>
    public class ContentOptions
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private int? maxCharactersPerResult;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "max_characters_per_result", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="ContentOptions"/> class.
        /// </summary>
        public ContentOptions()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ContentOptions"/> class.
        /// </summary>
        /// <param name="maxCharactersPerResult">max_characters_per_result.</param>
        public ContentOptions(
            int? maxCharactersPerResult = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();

            if (maxCharactersPerResult != null)
            {
                this.MaxCharactersPerResult = maxCharactersPerResult;
            }
        }

        /// <summary>
        /// Ceiling on the characters of any single result's content.
        /// Counts Unicode code points -- Rust `char`, Python `len(s)`, JavaScript `\[...s\].length`.
        /// Defaults to 20000, accepted range 100-1000000.
        /// </summary>
        [JsonProperty("max_characters_per_result")]
        public int? MaxCharactersPerResult
        {
            get
            {
                return this.maxCharactersPerResult;
            }

            set
            {
                this.shouldSerialize["max_characters_per_result"] = true;
                this.maxCharactersPerResult = value;
            }
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ContentOptions : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetMaxCharactersPerResult()
        {
            this.shouldSerialize["max_characters_per_result"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeMaxCharactersPerResult()
        {
            return this.shouldSerialize["max_characters_per_result"];
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"MaxCharactersPerResult = {(this.MaxCharactersPerResult == null ? "null" : this.MaxCharactersPerResult.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}