// <copyright file="CreateAgentRunRequest.cs" company="APIMatic">
// SeltzApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SeltzApi.Standard.Models
{
    /// <summary>
    /// CreateAgentRunRequest.
    /// </summary>
    public class CreateAgentRunRequest
    {
        private string apiKey;
        private string effort;
        private object outputSchema;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "api_key", false },
            { "effort", false },
            { "output_schema", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="CreateAgentRunRequest"/> class.
        /// </summary>
        public CreateAgentRunRequest()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CreateAgentRunRequest"/> class.
        /// </summary>
        /// <param name="apiKey">api_key.</param>
        /// <param name="effort">effort.</param>
        /// <param name="outputSchema">output_schema.</param>
        /// <param name="query">query.</param>
        public CreateAgentRunRequest(
            string apiKey = null,
            string effort = null,
            object outputSchema = null,
            string query = "")
        {

            if (apiKey != null)
            {
                this.ApiKey = apiKey;
            }

            if (effort != null)
            {
                this.Effort = effort;
            }

            if (outputSchema != null)
            {
                this.OutputSchema = outputSchema;
            }
            this.Query = query;
        }

        /// <summary>
        /// The API key, on gRPC requests. REST reads the `x-api-key` header instead.
        /// </summary>
        [JsonProperty("api_key")]
        public string ApiKey
        {
            get
            {
                return this.apiKey;
            }

            set
            {
                this.shouldSerialize["api_key"] = true;
                this.apiKey = value;
            }
        }

        /// <summary>
        /// Effort level: how much research the run may do, and its price. One of
        /// the configured level names (e.g. `low`, `medium`, `high`, `max`).
        /// Omitted = the default level.
        /// </summary>
        [JsonProperty("effort")]
        public string Effort
        {
            get
            {
                return this.effort;
            }

            set
            {
                this.shouldSerialize["effort"] = true;
                this.effort = value;
            }
        }

        /// <summary>
        /// Optional OpenAI-style `response_format` object requesting structured
        /// output: `{"type": "text" | "json_object" | "json_schema", ...}`, with
        /// `name` / `schema` / `strict` for type `json_schema`. A structured type
        /// adds `output.structured` and its `grounding` alongside the cited text;
        /// type `text` is accepted and requests no structure. On gRPC the object is
        /// JSON-encoded.
        /// </summary>
        [JsonProperty("output_schema")]
        public object OutputSchema
        {
            get
            {
                return this.outputSchema;
            }

            set
            {
                this.shouldSerialize["output_schema"] = true;
                this.outputSchema = value;
            }
        }

        /// <summary>
        /// The natural-language question. Instructions inside the query are
        /// followed.
        /// </summary>
        [JsonProperty("query", NullValueHandling = NullValueHandling.Ignore)]
        public string Query { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"CreateAgentRunRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetApiKey()
        {
            this.shouldSerialize["api_key"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetEffort()
        {
            this.shouldSerialize["effort"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetOutputSchema()
        {
            this.shouldSerialize["output_schema"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeApiKey()
        {
            return this.shouldSerialize["api_key"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeEffort()
        {
            return this.shouldSerialize["effort"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeOutputSchema()
        {
            return this.shouldSerialize["output_schema"];
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"ApiKey = {this.ApiKey ?? "null"}");
            toStringOutput.Add($"Effort = {this.Effort ?? "null"}");
            toStringOutput.Add($"OutputSchema = {(this.OutputSchema == null ? "null" : this.OutputSchema.ToString())}");
            toStringOutput.Add($"Query = {this.Query ?? "null"}");
        }
    }
}