// <copyright file="CreateMonitorRequest.cs" company="APIMatic">
// SeltzApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SeltzApi.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SeltzApi.Standard.Models
{
    /// <summary>
    /// CreateMonitorRequest.
    /// </summary>
    public class CreateMonitorRequest
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private string apiKey;
        private Models.Webhook webhook;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "api_key", false },
            { "webhook", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="CreateMonitorRequest"/> class.
        /// </summary>
        public CreateMonitorRequest()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CreateMonitorRequest"/> class.
        /// </summary>
        /// <param name="cadence">cadence.</param>
        /// <param name="apiKey">api_key.</param>
        /// <param name="name">name.</param>
        /// <param name="searchRequests">search_requests.</param>
        /// <param name="status">status.</param>
        /// <param name="webhook">webhook.</param>
        public CreateMonitorRequest(
            string cadence,
            string apiKey = null,
            string name = "",
            List<Models.SearchRequest> searchRequests = null,
            Models.MonitorStatus2? status = null,
            Models.Webhook webhook = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Cadence = cadence;

            if (apiKey != null)
            {
                this.ApiKey = apiKey;
            }
            this.Name = name;
            this.SearchRequests = searchRequests;
            this.Status = status;

            if (webhook != null)
            {
                this.Webhook = webhook;
            }
        }

        /// <summary>
        /// Gets or sets Cadence.
        /// </summary>
        [JsonProperty("cadence")]
        public string Cadence { get; set; }

        /// <summary>
        /// Gets or sets ApiKey.
        /// </summary>
        [JsonProperty("api_key")]
        public string ApiKey
        {
            get
            {
                return this.apiKey;
            }

            set
            {
                this.shouldSerialize["api_key"] = true;
                this.apiKey = value;
            }
        }

        /// <summary>
        /// Unique per org among live monitors; a deleted monitor's name becomes
        /// available again. At most 512 bytes of UTF-8.
        /// </summary>
        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        /// <summary>
        /// At least one, at most 1000. Every request runs on every run. A request
        /// with an `api_key` set, a blank `query`, or a body identical to another in
        /// the list is rejected.
        /// </summary>
        [JsonProperty("search_requests", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.SearchRequest> SearchRequests { get; set; }

        /// <summary>
        /// Gets or sets Status.
        /// </summary>
        [JsonProperty("status", NullValueHandling = NullValueHandling.Ignore)]
        public Models.MonitorStatus2? Status { get; set; }

        /// <summary>
        /// Gets or sets Webhook.
        /// </summary>
        [JsonProperty("webhook")]
        public Models.Webhook Webhook
        {
            get
            {
                return this.webhook;
            }

            set
            {
                this.shouldSerialize["webhook"] = true;
                this.webhook = value;
            }
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"CreateMonitorRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetApiKey()
        {
            this.shouldSerialize["api_key"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetWebhook()
        {
            this.shouldSerialize["webhook"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeApiKey()
        {
            return this.shouldSerialize["api_key"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeWebhook()
        {
            return this.shouldSerialize["webhook"];
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Cadence = {this.Cadence ?? "null"}");
            toStringOutput.Add($"ApiKey = {this.ApiKey ?? "null"}");
            toStringOutput.Add($"Name = {this.Name ?? "null"}");
            toStringOutput.Add($"SearchRequests = {(this.SearchRequests == null ? "null" : $"[{string.Join(", ", this.SearchRequests)} ]")}");
            toStringOutput.Add($"Status = {(this.Status == null ? "null" : this.Status.ToString())}");
            toStringOutput.Add($"Webhook = {(this.Webhook == null ? "null" : this.Webhook.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}