// <copyright file="Document.cs" company="APIMatic">
// SeltzApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SeltzApi.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SeltzApi.Standard.Models
{
    /// <summary>
    /// Document.
    /// </summary>
    public class Document
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private string content;
        private string publishedDate;
        private string url;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "content", false },
            { "published_date", false },
            { "url", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="Document"/> class.
        /// </summary>
        public Document()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Document"/> class.
        /// </summary>
        /// <param name="content">content.</param>
        /// <param name="publishedDate">published_date.</param>
        /// <param name="snippets">snippets.</param>
        /// <param name="url">url.</param>
        public Document(
            string content = null,
            string publishedDate = null,
            List<Models.Snippet> snippets = null,
            string url = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();

            if (content != null)
            {
                this.Content = content;
            }

            if (publishedDate != null)
            {
                this.PublishedDate = publishedDate;
            }
            this.Snippets = snippets;

            if (url != null)
            {
                this.Url = url;
            }
        }

        /// <summary>
        /// Gets or sets Content.
        /// </summary>
        [JsonProperty("content")]
        public string Content
        {
            get
            {
                return this.content;
            }

            set
            {
                this.shouldSerialize["content"] = true;
                this.content = value;
            }
        }

        /// <summary>
        /// Publication date as ISO 8601 string (e.g. "2024-03-15T00:00:00Z")
        /// </summary>
        [JsonProperty("published_date")]
        public string PublishedDate
        {
            get
            {
                return this.publishedDate;
            }

            set
            {
                this.shouldSerialize["published_date"] = true;
                this.publishedDate = value;
            }
        }

        /// <summary>
        /// The document's highest-scoring snippets, in the order they appear in the document.
        /// Populated when `fields.snippets` is selected and passages are available;
        /// empty otherwise.
        /// </summary>
        [JsonProperty("snippets", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.Snippet> Snippets { get; set; }

        /// <summary>
        /// Gets or sets Url.
        /// </summary>
        [JsonProperty("url")]
        public string Url
        {
            get
            {
                return this.url;
            }

            set
            {
                this.shouldSerialize["url"] = true;
                this.url = value;
            }
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Document : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetContent()
        {
            this.shouldSerialize["content"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetPublishedDate()
        {
            this.shouldSerialize["published_date"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetUrl()
        {
            this.shouldSerialize["url"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeContent()
        {
            return this.shouldSerialize["content"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializePublishedDate()
        {
            return this.shouldSerialize["published_date"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeUrl()
        {
            return this.shouldSerialize["url"];
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Content = {this.Content ?? "null"}");
            toStringOutput.Add($"PublishedDate = {this.PublishedDate ?? "null"}");
            toStringOutput.Add($"Snippets = {(this.Snippets == null ? "null" : $"[{string.Join(", ", this.Snippets)} ]")}");
            toStringOutput.Add($"Url = {this.Url ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}