// <copyright file="FetchError1.cs" company="APIMatic">
// SeltzApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SeltzApi.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SeltzApi.Standard.Models
{
    /// <summary>
    /// FetchError1.
    /// </summary>
    public class FetchError1
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FetchError1"/> class.
        /// </summary>
        public FetchError1()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FetchError1"/> class.
        /// </summary>
        /// <param name="code">code.</param>
        /// <param name="message">message.</param>
        public FetchError1(
            string code = "",
            string message = "")
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Code = code;
            this.Message = message;
        }

        /// <summary>
        /// A stable, machine-readable reason. A client must treat an unrecognized
        /// code as a generic failure rather than rejecting the result.
        /// Documented codes:
        /// "invalid_url"              -- not a parseable absolute URL.
        /// "unsupported_scheme"       -- parseable, but not `http` or `https`.
        /// "url_not_accessible"       -- DNS, connection, TLS, or navigation
        /// failure reaching the origin, or a host
        /// this service does not fetch.
        /// "timeout"                  -- the fetch did not finish within
        /// `timeout_ms`.
        /// "unsupported_content_type" -- the document is not an HTML page. PDFs,
        /// images, archives, and other binaries are
        /// out of scope. Refused from the URL before
        /// the fetch, or from the media type the
        /// origin declared after it.
        /// "extraction_failed"        -- the page was fetched, but no requested
        /// format could be produced from it.
        /// "upstream_error"           -- the fetch path itself failed. Ours, not
        /// the URL's.
        /// </summary>
        [JsonProperty("code", NullValueHandling = NullValueHandling.Ignore)]
        public string Code { get; set; }

        /// <summary>
        /// A human-readable explanation. Always set when this message is present:
        /// `FetchError` itself is optional on the result, so an absent error is
        /// absent whole, and there is no state where a failure arrives without a
        /// reason. For operators and logs. Never parse it -- branch on `code`. The
        /// wording of any given message may change at any time.
        /// </summary>
        [JsonProperty("message", NullValueHandling = NullValueHandling.Ignore)]
        public string Message { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"FetchError1 : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Code = {this.Code ?? "null"}");
            toStringOutput.Add($"Message = {this.Message ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}