// <copyright file="FetchStatus2.cs" company="APIMatic">
// SeltzApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SeltzApi.Standard.Models
{
    /// <summary>
    /// FetchStatus2.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum FetchStatus2
    {
        /// <summary>
        /// Ok.
        /// </summary>
        [EnumMember(Value = "ok")]
        Ok,

        /// <summary>
        /// Error.
        /// </summary>
        [EnumMember(Value = "error")]
        Error
    }
}