// <copyright file="FetchResult.cs" company="APIMatic">
// SeltzApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SeltzApi.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SeltzApi.Standard.Models
{
    /// <summary>
    /// FetchResult.
    /// </summary>
    public class FetchResult
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private string contentType;
        private Models.FetchError1 error;
        private string fetchedAt;
        private string finalUrl;
        private int? httpStatusCode;
        private string markdown;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "content_type", false },
            { "error", false },
            { "fetched_at", false },
            { "final_url", false },
            { "http_status_code", false },
            { "markdown", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="FetchResult"/> class.
        /// </summary>
        public FetchResult()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FetchResult"/> class.
        /// </summary>
        /// <param name="status">status.</param>
        /// <param name="contentType">content_type.</param>
        /// <param name="error">error.</param>
        /// <param name="fetchedAt">fetched_at.</param>
        /// <param name="finalUrl">final_url.</param>
        /// <param name="httpStatusCode">http_status_code.</param>
        /// <param name="markdown">markdown.</param>
        /// <param name="requestedUrl">requested_url.</param>
        public FetchResult(
            Models.FetchStatus2 status,
            string contentType = null,
            Models.FetchError1 error = null,
            string fetchedAt = null,
            string finalUrl = null,
            int? httpStatusCode = null,
            string markdown = null,
            string requestedUrl = "")
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();

            if (contentType != null)
            {
                this.ContentType = contentType;
            }

            if (error != null)
            {
                this.Error = error;
            }

            if (fetchedAt != null)
            {
                this.FetchedAt = fetchedAt;
            }

            if (finalUrl != null)
            {
                this.FinalUrl = finalUrl;
            }

            if (httpStatusCode != null)
            {
                this.HttpStatusCode = httpStatusCode;
            }

            if (markdown != null)
            {
                this.Markdown = markdown;
            }
            this.RequestedUrl = requestedUrl;
            this.Status = status;
        }

        /// <summary>
        /// The origin's declared media type for the main document, without
        /// parameters.
        /// Frequently unset, including on results that carry content. Never branch on
        /// it: `status` says whether a result carries content.
        /// </summary>
        [JsonProperty("content_type")]
        public string ContentType
        {
            get
            {
                return this.contentType;
            }

            set
            {
                this.shouldSerialize["content_type"] = true;
                this.contentType = value;
            }
        }

        /// <summary>
        /// Gets or sets Error.
        /// </summary>
        [JsonProperty("error")]
        public Models.FetchError1 Error
        {
            get
            {
                return this.error;
            }

            set
            {
                this.shouldSerialize["error"] = true;
                this.error = value;
            }
        }

        /// <summary>
        /// Gets or sets FetchedAt.
        /// </summary>
        [JsonProperty("fetched_at")]
        public string FetchedAt
        {
            get
            {
                return this.fetchedAt;
            }

            set
            {
                this.shouldSerialize["fetched_at"] = true;
                this.fetchedAt = value;
            }
        }

        /// <summary>
        /// The URL the content actually came from, after HTTP redirects and any
        /// client-side navigation. Equal to `requested_url` when nothing redirected.
        /// Set on a result whose `status` is ERROR only when the failure happened
        /// after the origin answered, such as a page this service could not extract.
        /// Unset when the URL was never reached.
        /// </summary>
        [JsonProperty("final_url")]
        public string FinalUrl
        {
            get
            {
                return this.finalUrl;
            }

            set
            {
                this.shouldSerialize["final_url"] = true;
                this.finalUrl = value;
            }
        }

        /// <summary>
        /// The origin's HTTP status code for the main document. Unset when no network
        /// response was observed for the navigation.
        /// An HTTP error status is not a fetch failure: this service renders the
        /// origin's error page, so a 404 arrives as an OK result carrying 404. On a
        /// result whose `status` is ERROR, this follows `final_url` - set only when
        /// the failure happened after the origin answered.
        /// </summary>
        [JsonProperty("http_status_code")]
        public int? HttpStatusCode
        {
            get
            {
                return this.httpStatusCode;
            }

            set
            {
                this.shouldSerialize["http_status_code"] = true;
                this.httpStatusCode = value;
            }
        }

        /// <summary>
        /// The page's main content as Markdown, with boilerplate removed.
        /// </summary>
        [JsonProperty("markdown")]
        public string Markdown
        {
            get
            {
                return this.markdown;
            }

            set
            {
                this.shouldSerialize["markdown"] = true;
                this.markdown = value;
            }
        }

        /// <summary>
        /// The URL this answers, echoed verbatim from the request -- byte for byte,
        /// never normalized, and never the post-redirect URL. This is the correlation
        /// key. Where redirects landed is `final_url`.
        /// </summary>
        [JsonProperty("requested_url", NullValueHandling = NullValueHandling.Ignore)]
        public string RequestedUrl { get; set; }

        /// <summary>
        /// Gets or sets Status.
        /// </summary>
        [JsonProperty("status")]
        public Models.FetchStatus2 Status { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"FetchResult : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetContentType()
        {
            this.shouldSerialize["content_type"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetError()
        {
            this.shouldSerialize["error"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetFetchedAt()
        {
            this.shouldSerialize["fetched_at"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetFinalUrl()
        {
            this.shouldSerialize["final_url"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetHttpStatusCode()
        {
            this.shouldSerialize["http_status_code"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetMarkdown()
        {
            this.shouldSerialize["markdown"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeContentType()
        {
            return this.shouldSerialize["content_type"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeError()
        {
            return this.shouldSerialize["error"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeFetchedAt()
        {
            return this.shouldSerialize["fetched_at"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeFinalUrl()
        {
            return this.shouldSerialize["final_url"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeHttpStatusCode()
        {
            return this.shouldSerialize["http_status_code"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeMarkdown()
        {
            return this.shouldSerialize["markdown"];
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"ContentType = {this.ContentType ?? "null"}");
            toStringOutput.Add($"Error = {(this.Error == null ? "null" : this.Error.ToString())}");
            toStringOutput.Add($"FetchedAt = {this.FetchedAt ?? "null"}");
            toStringOutput.Add($"FinalUrl = {this.FinalUrl ?? "null"}");
            toStringOutput.Add($"HttpStatusCode = {(this.HttpStatusCode == null ? "null" : this.HttpStatusCode.ToString())}");
            toStringOutput.Add($"Markdown = {this.Markdown ?? "null"}");
            toStringOutput.Add($"RequestedUrl = {this.RequestedUrl ?? "null"}");
            toStringOutput.Add($"Status = {this.Status}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}