// <copyright file="FetchRequest.cs" company="APIMatic">
// SeltzApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SeltzApi.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SeltzApi.Standard.Models
{
    /// <summary>
    /// FetchRequest.
    /// </summary>
    public class FetchRequest
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private string apiKey;
        private string tier;
        private int? timeoutMs;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "api_key", false },
            { "tier", false },
            { "timeout_ms", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="FetchRequest"/> class.
        /// </summary>
        public FetchRequest()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FetchRequest"/> class.
        /// </summary>
        /// <param name="apiKey">api_key.</param>
        /// <param name="formats">formats.</param>
        /// <param name="tier">tier.</param>
        /// <param name="timeoutMs">timeout_ms.</param>
        /// <param name="urls">urls.</param>
        public FetchRequest(
            string apiKey = null,
            List<string> formats = null,
            string tier = null,
            int? timeoutMs = null,
            List<string> urls = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();

            if (apiKey != null)
            {
                this.ApiKey = apiKey;
            }
            this.Formats = formats;

            if (tier != null)
            {
                this.Tier = tier;
            }

            if (timeoutMs != null)
            {
                this.TimeoutMs = timeoutMs;
            }
            this.Urls = urls;
        }

        /// <summary>
        /// API key to access the service. Either this or the `x-api-key` header must
        /// be supplied on the HTTP surface; the header takes precedence and is the
        /// documented path. On gRPC this field is the only carrier.
        /// Each URL that comes back with the OK status is billed. A URL that comes
        /// back with an error is not. The call is refused up front unless the balance
        /// covers the whole batch.
        /// </summary>
        [JsonProperty("api_key")]
        public string ApiKey
        {
            get
            {
                return this.apiKey;
            }

            set
            {
                this.shouldSerialize["api_key"] = true;
                this.apiKey = value;
            }
        }

        /// <summary>
        /// Representations to return, as documented format names.
        /// Omitted, or sent empty, means `\["markdown"\]` -- a repeated field carries
        /// no presence, so the two are the same request and neither means "no
        /// formats".
        /// Documented names:
        /// "markdown" -- the main content as Markdown, boilerplate removed.
        /// An unrecognized name is rejected.
        /// </summary>
        [JsonProperty("formats", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> Formats { get; set; }

        /// <summary>
        /// The service tier, which selects the price. Send `"pro"`. Unset resolves to
        /// `"pro"`.
        /// An unrecognized value is rejected rather than defaulted, because the value
        /// selects a price. The name is matched exactly.
        /// </summary>
        [JsonProperty("tier")]
        public string Tier
        {
            get
            {
                return this.tier;
            }

            set
            {
                this.shouldSerialize["tier"] = true;
                this.tier = value;
            }
        }

        /// <summary>
        /// Wall-clock budget for one URL, in milliseconds.
        /// Applies to each URL, not to the batch. A URL that exceeds the budget gets
        /// `error.code = "timeout"`; the others in the same request are unaffected.
        /// Unset means 75000, which is also the maximum; a larger value is served as
        /// 75000, and a value below 1000 is served as 1000.
        /// </summary>
        [JsonProperty("timeout_ms")]
        public int? TimeoutMs
        {
            get
            {
                return this.timeoutMs;
            }

            set
            {
                this.shouldSerialize["timeout_ms"] = true;
                this.timeoutMs = value;
            }
        }

        /// <summary>
        /// The URLs to fetch. At least one, at most 20.
        /// An empty list, more than 20 entries, a duplicate entry, a blank or padded
        /// entry, or an entry over 2048 bytes is rejected before any billing --
        /// duplicates because `FetchResult.requested_url` is the correlation key and
        /// a repeated key is ambiguous.
        /// Everything else is reported inside a `200` as that URL's error result: a
        /// value that is not an absolute `http` or `https` URL, a host that does not
        /// resolve or that this service will not fetch, an origin that refuses, and a
        /// document that is not an HTML page.
        /// </summary>
        [JsonProperty("urls", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> Urls { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"FetchRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetApiKey()
        {
            this.shouldSerialize["api_key"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetTier()
        {
            this.shouldSerialize["tier"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetTimeoutMs()
        {
            this.shouldSerialize["timeout_ms"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeApiKey()
        {
            return this.shouldSerialize["api_key"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeTier()
        {
            return this.shouldSerialize["tier"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeTimeoutMs()
        {
            return this.shouldSerialize["timeout_ms"];
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"ApiKey = {this.ApiKey ?? "null"}");
            toStringOutput.Add($"Formats = {(this.Formats == null ? "null" : $"[{string.Join(", ", this.Formats)} ]")}");
            toStringOutput.Add($"Tier = {this.Tier ?? "null"}");
            toStringOutput.Add($"TimeoutMs = {(this.TimeoutMs == null ? "null" : this.TimeoutMs.ToString())}");
            toStringOutput.Add($"Urls = {(this.Urls == null ? "null" : $"[{string.Join(", ", this.Urls)} ]")}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}