// <copyright file="ListAgentRunsResponse.cs" company="APIMatic">
// SeltzApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SeltzApi.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SeltzApi.Standard.Models
{
    /// <summary>
    /// ListAgentRunsResponse.
    /// </summary>
    public class ListAgentRunsResponse
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private string next;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "next", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="ListAgentRunsResponse"/> class.
        /// </summary>
        public ListAgentRunsResponse()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ListAgentRunsResponse"/> class.
        /// </summary>
        /// <param name="next">next.</param>
        /// <param name="runs">runs.</param>
        public ListAgentRunsResponse(
            string next = null,
            List<Models.AgentRun> runs = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();

            if (next != null)
            {
                this.Next = next;
            }
            this.Runs = runs;
        }

        /// <summary>
        /// Cursor to the next page. Unset on the last page.
        /// </summary>
        [JsonProperty("next")]
        public string Next
        {
            get
            {
                return this.next;
            }

            set
            {
                this.shouldSerialize["next"] = true;
                this.next = value;
            }
        }

        /// <summary>
        /// The page's runs, newest first.
        /// </summary>
        [JsonProperty("runs", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.AgentRun> Runs { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ListAgentRunsResponse : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetNext()
        {
            this.shouldSerialize["next"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeNext()
        {
            return this.shouldSerialize["next"];
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Next = {this.Next ?? "null"}");
            toStringOutput.Add($"Runs = {(this.Runs == null ? "null" : $"[{string.Join(", ", this.Runs)} ]")}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}