// <copyright file="MonitorSearchRequest.cs" company="APIMatic">
// SeltzApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SeltzApi.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SeltzApi.Standard.Models
{
    /// <summary>
    /// MonitorSearchRequest.
    /// </summary>
    public class MonitorSearchRequest
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private string lastSuccessAt;
        private Models.SearchRequest request;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "last_success_at", false },
            { "request", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="MonitorSearchRequest"/> class.
        /// </summary>
        public MonitorSearchRequest()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MonitorSearchRequest"/> class.
        /// </summary>
        /// <param name="consecutiveFailures">consecutive_failures.</param>
        /// <param name="lastSuccessAt">last_success_at.</param>
        /// <param name="request">request.</param>
        /// <param name="requestId">request_id.</param>
        public MonitorSearchRequest(
            long? consecutiveFailures = 0L,
            string lastSuccessAt = null,
            Models.SearchRequest request = null,
            string requestId = "")
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.ConsecutiveFailures = consecutiveFailures;

            if (lastSuccessAt != null)
            {
                this.LastSuccessAt = lastSuccessAt;
            }

            if (request != null)
            {
                this.Request = request;
            }
            this.RequestId = requestId;
        }

        /// <summary>
        /// Consecutive failed runs for this request.
        /// </summary>
        [JsonProperty("consecutive_failures", NullValueHandling = NullValueHandling.Ignore)]
        public long? ConsecutiveFailures { get; set; }

        /// <summary>
        /// Gets or sets LastSuccessAt.
        /// </summary>
        [JsonProperty("last_success_at")]
        public string LastSuccessAt
        {
            get
            {
                return this.lastSuccessAt;
            }

            set
            {
                this.shouldSerialize["last_success_at"] = true;
                this.lastSuccessAt = value;
            }
        }

        /// <summary>
        /// Gets or sets Request.
        /// </summary>
        [JsonProperty("request")]
        public Models.SearchRequest Request
        {
            get
            {
                return this.request;
            }

            set
            {
                this.shouldSerialize["request"] = true;
                this.request = value;
            }
        }

        /// <summary>
        /// Gets or sets RequestId.
        /// </summary>
        [JsonProperty("request_id", NullValueHandling = NullValueHandling.Ignore)]
        public string RequestId { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"MonitorSearchRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetLastSuccessAt()
        {
            this.shouldSerialize["last_success_at"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetRequest()
        {
            this.shouldSerialize["request"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeLastSuccessAt()
        {
            return this.shouldSerialize["last_success_at"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeRequest()
        {
            return this.shouldSerialize["request"];
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"ConsecutiveFailures = {(this.ConsecutiveFailures == null ? "null" : this.ConsecutiveFailures.ToString())}");
            toStringOutput.Add($"LastSuccessAt = {this.LastSuccessAt ?? "null"}");
            toStringOutput.Add($"Request = {(this.Request == null ? "null" : this.Request.ToString())}");
            toStringOutput.Add($"RequestId = {this.RequestId ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}