// <copyright file="Monitor.cs" company="APIMatic">
// SeltzApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SeltzApi.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SeltzApi.Standard.Models
{
    /// <summary>
    /// Monitor.
    /// </summary>
    public class Monitor
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private string createdAt;
        private string updatedAt;
        private Models.Webhook webhook;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "created_at", false },
            { "updated_at", false },
            { "webhook", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="Monitor"/> class.
        /// </summary>
        public Monitor()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Monitor"/> class.
        /// </summary>
        /// <param name="cadence">cadence.</param>
        /// <param name="status">status.</param>
        /// <param name="createdAt">created_at.</param>
        /// <param name="monitorId">monitor_id.</param>
        /// <param name="name">name.</param>
        /// <param name="searchRequests">search_requests.</param>
        /// <param name="updatedAt">updated_at.</param>
        /// <param name="webhook">webhook.</param>
        public Monitor(
            string cadence,
            Models.MonitorStatus status,
            string createdAt = null,
            string monitorId = "",
            string name = "",
            List<Models.MonitorSearchRequest> searchRequests = null,
            string updatedAt = null,
            Models.Webhook webhook = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Cadence = cadence;

            if (createdAt != null)
            {
                this.CreatedAt = createdAt;
            }
            this.MonitorId = monitorId;
            this.Name = name;
            this.SearchRequests = searchRequests;
            this.Status = status;

            if (updatedAt != null)
            {
                this.UpdatedAt = updatedAt;
            }

            if (webhook != null)
            {
                this.Webhook = webhook;
            }
        }

        /// <summary>
        /// Gets or sets Cadence.
        /// </summary>
        [JsonProperty("cadence")]
        public string Cadence { get; set; }

        /// <summary>
        /// Gets or sets CreatedAt.
        /// </summary>
        [JsonProperty("created_at")]
        public string CreatedAt
        {
            get
            {
                return this.createdAt;
            }

            set
            {
                this.shouldSerialize["created_at"] = true;
                this.createdAt = value;
            }
        }

        /// <summary>
        /// Gets or sets MonitorId.
        /// </summary>
        [JsonProperty("monitor_id", NullValueHandling = NullValueHandling.Ignore)]
        public string MonitorId { get; set; }

        /// <summary>
        /// Gets or sets Name.
        /// </summary>
        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets SearchRequests.
        /// </summary>
        [JsonProperty("search_requests", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.MonitorSearchRequest> SearchRequests { get; set; }

        /// <summary>
        /// Gets or sets Status.
        /// </summary>
        [JsonProperty("status")]
        public Models.MonitorStatus Status { get; set; }

        /// <summary>
        /// Gets or sets UpdatedAt.
        /// </summary>
        [JsonProperty("updated_at")]
        public string UpdatedAt
        {
            get
            {
                return this.updatedAt;
            }

            set
            {
                this.shouldSerialize["updated_at"] = true;
                this.updatedAt = value;
            }
        }

        /// <summary>
        /// Gets or sets Webhook.
        /// </summary>
        [JsonProperty("webhook")]
        public Models.Webhook Webhook
        {
            get
            {
                return this.webhook;
            }

            set
            {
                this.shouldSerialize["webhook"] = true;
                this.webhook = value;
            }
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Monitor : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetCreatedAt()
        {
            this.shouldSerialize["created_at"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetUpdatedAt()
        {
            this.shouldSerialize["updated_at"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetWebhook()
        {
            this.shouldSerialize["webhook"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeCreatedAt()
        {
            return this.shouldSerialize["created_at"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeUpdatedAt()
        {
            return this.shouldSerialize["updated_at"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeWebhook()
        {
            return this.shouldSerialize["webhook"];
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Cadence = {this.Cadence ?? "null"}");
            toStringOutput.Add($"CreatedAt = {this.CreatedAt ?? "null"}");
            toStringOutput.Add($"MonitorId = {this.MonitorId ?? "null"}");
            toStringOutput.Add($"Name = {this.Name ?? "null"}");
            toStringOutput.Add($"SearchRequests = {(this.SearchRequests == null ? "null" : $"[{string.Join(", ", this.SearchRequests)} ]")}");
            toStringOutput.Add($"Status = {this.Status}");
            toStringOutput.Add($"UpdatedAt = {this.UpdatedAt ?? "null"}");
            toStringOutput.Add($"Webhook = {(this.Webhook == null ? "null" : this.Webhook.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}