// <copyright file="Record.cs" company="APIMatic">
// SeltzApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SeltzApi.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SeltzApi.Standard.Models
{
    /// <summary>
    /// Record.
    /// </summary>
    public class Record
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private string firstSeenAt;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "first_seen_at", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="Record"/> class.
        /// </summary>
        public Record()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Record"/> class.
        /// </summary>
        /// <param name="searchResult">search_result.</param>
        /// <param name="type">type.</param>
        /// <param name="firstSeenAt">first_seen_at.</param>
        /// <param name="recordId">record_id.</param>
        /// <param name="runId">run_id.</param>
        public Record(
            Models.SearchRecord searchResult,
            Models.RecordType type,
            string firstSeenAt = null,
            string recordId = "0",
            string runId = "0")
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.SearchResult = searchResult;

            if (firstSeenAt != null)
            {
                this.FirstSeenAt = firstSeenAt;
            }
            this.RecordId = recordId;
            this.RunId = runId;
            this.Type = type;
        }

        /// <summary>
        /// Gets or sets SearchResult.
        /// </summary>
        [JsonProperty("search_result")]
        public Models.SearchRecord SearchResult { get; set; }

        /// <summary>
        /// Gets or sets FirstSeenAt.
        /// </summary>
        [JsonProperty("first_seen_at")]
        public string FirstSeenAt
        {
            get
            {
                return this.firstSeenAt;
            }

            set
            {
                this.shouldSerialize["first_seen_at"] = true;
                this.firstSeenAt = value;
            }
        }

        /// <summary>
        /// Gets or sets RecordId.
        /// </summary>
        [JsonProperty("record_id", NullValueHandling = NullValueHandling.Ignore)]
        public string RecordId { get; set; }

        /// <summary>
        /// Gets or sets RunId.
        /// </summary>
        [JsonProperty("run_id", NullValueHandling = NullValueHandling.Ignore)]
        public string RunId { get; set; }

        /// <summary>
        /// Gets or sets Type.
        /// </summary>
        [JsonProperty("type")]
        public Models.RecordType Type { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Record : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetFirstSeenAt()
        {
            this.shouldSerialize["first_seen_at"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeFirstSeenAt()
        {
            return this.shouldSerialize["first_seen_at"];
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"SearchResult = {(this.SearchResult == null ? "null" : this.SearchResult.ToString())}");
            toStringOutput.Add($"FirstSeenAt = {this.FirstSeenAt ?? "null"}");
            toStringOutput.Add($"RecordId = {this.RecordId ?? "null"}");
            toStringOutput.Add($"RunId = {this.RunId ?? "null"}");
            toStringOutput.Add($"Type = {this.Type}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}