// <copyright file="RecordType.cs" company="APIMatic">
// SeltzApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SeltzApi.Standard.Models
{
    /// <summary>
    /// RecordType.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum RecordType
    {
        /// <summary>
        /// SearchResult.
        /// </summary>
        [EnumMember(Value = "search_result")]
        SearchResult
    }
}