// <copyright file="RequestStatus.cs" company="APIMatic">
// SeltzApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SeltzApi.Standard.Models
{
    /// <summary>
    /// RequestStatus.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum RequestStatus
    {
        /// <summary>
        /// Ok.
        /// </summary>
        [EnumMember(Value = "ok")]
        Ok,

        /// <summary>
        /// Failed.
        /// </summary>
        [EnumMember(Value = "failed")]
        Failed
    }
}