// <copyright file="Run.cs" company="APIMatic">
// SeltzApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SeltzApi.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SeltzApi.Standard.Models
{
    /// <summary>
    /// Run.
    /// </summary>
    public class Run
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private string completedAt;
        private string startedAt;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "completed_at", false },
            { "started_at", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="Run"/> class.
        /// </summary>
        public Run()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Run"/> class.
        /// </summary>
        /// <param name="status">status.</param>
        /// <param name="completedAt">completed_at.</param>
        /// <param name="firstRecordId">first_record_id.</param>
        /// <param name="lastRecordId">last_record_id.</param>
        /// <param name="monitorId">monitor_id.</param>
        /// <param name="recordCount">record_count.</param>
        /// <param name="requestsFailed">requests_failed.</param>
        /// <param name="requestsOk">requests_ok.</param>
        /// <param name="requestsTotal">requests_total.</param>
        /// <param name="runId">run_id.</param>
        /// <param name="startedAt">started_at.</param>
        /// <param name="statusReason">status_reason.</param>
        public Run(
            Models.RunStatus status,
            string completedAt = null,
            string firstRecordId = "0",
            string lastRecordId = "0",
            string monitorId = "",
            long? recordCount = 0L,
            long? requestsFailed = 0L,
            long? requestsOk = 0L,
            long? requestsTotal = 0L,
            string runId = "0",
            string startedAt = null,
            string statusReason = "")
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();

            if (completedAt != null)
            {
                this.CompletedAt = completedAt;
            }
            this.FirstRecordId = firstRecordId;
            this.LastRecordId = lastRecordId;
            this.MonitorId = monitorId;
            this.RecordCount = recordCount;
            this.RequestsFailed = requestsFailed;
            this.RequestsOk = requestsOk;
            this.RequestsTotal = requestsTotal;
            this.RunId = runId;

            if (startedAt != null)
            {
                this.StartedAt = startedAt;
            }
            this.Status = status;
            this.StatusReason = statusReason;
        }

        /// <summary>
        /// Gets or sets CompletedAt.
        /// </summary>
        [JsonProperty("completed_at")]
        public string CompletedAt
        {
            get
            {
                return this.completedAt;
            }

            set
            {
                this.shouldSerialize["completed_at"] = true;
                this.completedAt = value;
            }
        }

        /// <summary>
        /// The lowest `record_id` this run produced. Records are not contiguous; use
        /// `record_count` for the count.
        /// </summary>
        [JsonProperty("first_record_id", NullValueHandling = NullValueHandling.Ignore)]
        public string FirstRecordId { get; set; }

        /// <summary>
        /// The highest `record_id` this run produced. Records are not contiguous; use
        /// `record_count` for the count.
        /// </summary>
        [JsonProperty("last_record_id", NullValueHandling = NullValueHandling.Ignore)]
        public string LastRecordId { get; set; }

        /// <summary>
        /// Gets or sets MonitorId.
        /// </summary>
        [JsonProperty("monitor_id", NullValueHandling = NullValueHandling.Ignore)]
        public string MonitorId { get; set; }

        /// <summary>
        /// Gets or sets RecordCount.
        /// </summary>
        [JsonProperty("record_count", NullValueHandling = NullValueHandling.Ignore)]
        public long? RecordCount { get; set; }

        /// <summary>
        /// Gets or sets RequestsFailed.
        /// </summary>
        [JsonProperty("requests_failed", NullValueHandling = NullValueHandling.Ignore)]
        public long? RequestsFailed { get; set; }

        /// <summary>
        /// Gets or sets RequestsOk.
        /// </summary>
        [JsonProperty("requests_ok", NullValueHandling = NullValueHandling.Ignore)]
        public long? RequestsOk { get; set; }

        /// <summary>
        /// Gets or sets RequestsTotal.
        /// </summary>
        [JsonProperty("requests_total", NullValueHandling = NullValueHandling.Ignore)]
        public long? RequestsTotal { get; set; }

        /// <summary>
        /// Gets or sets RunId.
        /// </summary>
        [JsonProperty("run_id", NullValueHandling = NullValueHandling.Ignore)]
        public string RunId { get; set; }

        /// <summary>
        /// Gets or sets StartedAt.
        /// </summary>
        [JsonProperty("started_at")]
        public string StartedAt
        {
            get
            {
                return this.startedAt;
            }

            set
            {
                this.shouldSerialize["started_at"] = true;
                this.startedAt = value;
            }
        }

        /// <summary>
        /// Gets or sets Status.
        /// </summary>
        [JsonProperty("status")]
        public Models.RunStatus Status { get; set; }

        /// <summary>
        /// Prose for a human, empty when completed.
        /// </summary>
        [JsonProperty("status_reason", NullValueHandling = NullValueHandling.Ignore)]
        public string StatusReason { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Run : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetCompletedAt()
        {
            this.shouldSerialize["completed_at"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetStartedAt()
        {
            this.shouldSerialize["started_at"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeCompletedAt()
        {
            return this.shouldSerialize["completed_at"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeStartedAt()
        {
            return this.shouldSerialize["started_at"];
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"CompletedAt = {this.CompletedAt ?? "null"}");
            toStringOutput.Add($"FirstRecordId = {this.FirstRecordId ?? "null"}");
            toStringOutput.Add($"LastRecordId = {this.LastRecordId ?? "null"}");
            toStringOutput.Add($"MonitorId = {this.MonitorId ?? "null"}");
            toStringOutput.Add($"RecordCount = {(this.RecordCount == null ? "null" : this.RecordCount.ToString())}");
            toStringOutput.Add($"RequestsFailed = {(this.RequestsFailed == null ? "null" : this.RequestsFailed.ToString())}");
            toStringOutput.Add($"RequestsOk = {(this.RequestsOk == null ? "null" : this.RequestsOk.ToString())}");
            toStringOutput.Add($"RequestsTotal = {(this.RequestsTotal == null ? "null" : this.RequestsTotal.ToString())}");
            toStringOutput.Add($"RunId = {this.RunId ?? "null"}");
            toStringOutput.Add($"StartedAt = {this.StartedAt ?? "null"}");
            toStringOutput.Add($"Status = {this.Status}");
            toStringOutput.Add($"StatusReason = {this.StatusReason ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}