// <copyright file="RunRequest.cs" company="APIMatic">
// SeltzApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SeltzApi.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SeltzApi.Standard.Models
{
    /// <summary>
    /// RunRequest.
    /// </summary>
    public class RunRequest
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private string completedAt;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "completed_at", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="RunRequest"/> class.
        /// </summary>
        public RunRequest()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RunRequest"/> class.
        /// </summary>
        /// <param name="status">status.</param>
        /// <param name="completedAt">completed_at.</param>
        /// <param name="newRecords">new_records.</param>
        /// <param name="reason">reason.</param>
        /// <param name="requestId">request_id.</param>
        /// <param name="resultsReturned">results_returned.</param>
        public RunRequest(
            Models.RequestStatus status,
            string completedAt = null,
            long? newRecords = 0L,
            string reason = "",
            string requestId = "",
            long? resultsReturned = 0L)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();

            if (completedAt != null)
            {
                this.CompletedAt = completedAt;
            }
            this.NewRecords = newRecords;
            this.Reason = reason;
            this.RequestId = requestId;
            this.ResultsReturned = resultsReturned;
            this.Status = status;
        }

        /// <summary>
        /// Gets or sets CompletedAt.
        /// </summary>
        [JsonProperty("completed_at")]
        public string CompletedAt
        {
            get
            {
                return this.completedAt;
            }

            set
            {
                this.shouldSerialize["completed_at"] = true;
                this.completedAt = value;
            }
        }

        /// <summary>
        /// Gets or sets NewRecords.
        /// </summary>
        [JsonProperty("new_records", NullValueHandling = NullValueHandling.Ignore)]
        public long? NewRecords { get; set; }

        /// <summary>
        /// Why the request failed, empty when it succeeded. Not machine-readable.
        /// </summary>
        [JsonProperty("reason", NullValueHandling = NullValueHandling.Ignore)]
        public string Reason { get; set; }

        /// <summary>
        /// Gets or sets RequestId.
        /// </summary>
        [JsonProperty("request_id", NullValueHandling = NullValueHandling.Ignore)]
        public string RequestId { get; set; }

        /// <summary>
        /// Gets or sets ResultsReturned.
        /// </summary>
        [JsonProperty("results_returned", NullValueHandling = NullValueHandling.Ignore)]
        public long? ResultsReturned { get; set; }

        /// <summary>
        /// Gets or sets Status.
        /// </summary>
        [JsonProperty("status")]
        public Models.RequestStatus Status { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"RunRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetCompletedAt()
        {
            this.shouldSerialize["completed_at"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeCompletedAt()
        {
            return this.shouldSerialize["completed_at"];
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"CompletedAt = {this.CompletedAt ?? "null"}");
            toStringOutput.Add($"NewRecords = {(this.NewRecords == null ? "null" : this.NewRecords.ToString())}");
            toStringOutput.Add($"Reason = {this.Reason ?? "null"}");
            toStringOutput.Add($"RequestId = {this.RequestId ?? "null"}");
            toStringOutput.Add($"ResultsReturned = {(this.ResultsReturned == null ? "null" : this.ResultsReturned.ToString())}");
            toStringOutput.Add($"Status = {this.Status}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}