// <copyright file="RunStatus.cs" company="APIMatic">
// SeltzApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SeltzApi.Standard.Models
{
    /// <summary>
    /// RunStatus.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum RunStatus
    {
        /// <summary>
        /// Completed.
        /// </summary>
        [EnumMember(Value = "completed")]
        Completed,

        /// <summary>
        /// Partial.
        /// </summary>
        [EnumMember(Value = "partial")]
        Partial,

        /// <summary>
        /// Failed.
        /// </summary>
        [EnumMember(Value = "failed")]
        Failed,

        /// <summary>
        /// Skipped.
        /// </summary>
        [EnumMember(Value = "skipped")]
        Skipped
    }
}