// <copyright file="RunState2.cs" company="APIMatic">
// SeltzApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SeltzApi.Standard.Models
{
    /// <summary>
    /// RunState2.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum RunState2
    {
        /// <summary>
        /// Idle.
        /// </summary>
        [EnumMember(Value = "idle")]
        Idle,

        /// <summary>
        /// Running.
        /// </summary>
        [EnumMember(Value = "running")]
        Running,

        /// <summary>
        /// Unknown.
        /// </summary>
        [EnumMember(Value = "unknown")]
        Unknown
    }
}