// <copyright file="SearchRequest.cs" company="APIMatic">
// SeltzApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SeltzApi.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SeltzApi.Standard.Models
{
    /// <summary>
    /// SearchRequest.
    /// </summary>
    public class SearchRequest
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private string apiKey;
        private Models.Fields2 fields;
        private string fromDate;
        private int? maxResults;
        private string scope;
        private string tier;
        private string toDate;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "api_key", false },
            { "fields", false },
            { "from_date", false },
            { "max_results", false },
            { "scope", false },
            { "tier", false },
            { "to_date", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="SearchRequest"/> class.
        /// </summary>
        public SearchRequest()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SearchRequest"/> class.
        /// </summary>
        /// <param name="apiKey">api_key.</param>
        /// <param name="excludeDomains">exclude_domains.</param>
        /// <param name="fields">fields.</param>
        /// <param name="fromDate">from_date.</param>
        /// <param name="includeDomains">include_domains.</param>
        /// <param name="maxResults">max_results.</param>
        /// <param name="query">query.</param>
        /// <param name="scope">scope.</param>
        /// <param name="tier">tier.</param>
        /// <param name="toDate">to_date.</param>
        public SearchRequest(
            string apiKey = null,
            List<string> excludeDomains = null,
            Models.Fields2 fields = null,
            string fromDate = null,
            List<string> includeDomains = null,
            int? maxResults = null,
            string query = "",
            string scope = null,
            string tier = null,
            string toDate = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();

            if (apiKey != null)
            {
                this.ApiKey = apiKey;
            }
            this.ExcludeDomains = excludeDomains;

            if (fields != null)
            {
                this.Fields = fields;
            }

            if (fromDate != null)
            {
                this.FromDate = fromDate;
            }
            this.IncludeDomains = includeDomains;

            if (maxResults != null)
            {
                this.MaxResults = maxResults;
            }
            this.Query = query;

            if (scope != null)
            {
                this.Scope = scope;
            }

            if (tier != null)
            {
                this.Tier = tier;
            }

            if (toDate != null)
            {
                this.ToDate = toDate;
            }
        }

        /// <summary>
        /// API key. On the HTTP surface, either this or the `x-api-key` header must
        /// be supplied; the header takes precedence.
        /// </summary>
        [JsonProperty("api_key")]
        public string ApiKey
        {
            get
            {
                return this.apiKey;
            }

            set
            {
                this.shouldSerialize["api_key"] = true;
                this.apiKey = value;
            }
        }

        /// <summary>
        /// Exclude results from these domains
        /// </summary>
        [JsonProperty("exclude_domains", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> ExcludeDomains { get; set; }

        /// <summary>
        /// Gets or sets Fields.
        /// </summary>
        [JsonProperty("fields")]
        public Models.Fields2 Fields
        {
            get
            {
                return this.fields;
            }

            set
            {
                this.shouldSerialize["fields"] = true;
                this.fields = value;
            }
        }

        /// <summary>
        /// Only include results published on or after this point. UTC throughout.
        /// A date "2025-10-28", a datetime "2025-10-28T23:00:00" or
        /// "2025-10-28T23:00:00Z", or an offset from "now", which is the time the
        /// request is served: "now" itself, or "now-" and one duration such as
        /// "now-7d" for the past week. A datetime written without a zone is read as
        /// UTC, and a date written without a time is the start of that day.
        /// Offset units are s = second, m = minute, h = hour, d = 24 h, w = 7 d,
        /// M = one calendar month and y = one calendar year. A unit and a count are
        /// both required, and the case carries meaning.
        /// A month and a year step the calendar rather than a fixed number of
        /// seconds, and the day of the month is clamped to the length of the target
        /// month. So "now-1M" from the 31st of March lands on the 28th or 29th of
        /// February.
        /// An offset is a filter, not a freshness guarantee: the corpus refreshes on
        /// its own cadence, so a window of an hour or two can return nothing.
        /// Only a single offset before "now" is accepted. Rounding, several terms in
        /// one value, a "+" offset, and any anchor other than "now" are rejected.
        /// </summary>
        [JsonProperty("from_date")]
        public string FromDate
        {
            get
            {
                return this.fromDate;
            }

            set
            {
                this.shouldSerialize["from_date"] = true;
                this.fromDate = value;
            }
        }

        /// <summary>
        /// Include only results from these domains (e.g., \["google.com", "example.com"\])
        /// </summary>
        [JsonProperty("include_domains", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> IncludeDomains { get; set; }

        /// <summary>
        /// Maximum number of results to return. Defaults to 10. A larger value is
        /// served as 1000.
        /// </summary>
        [JsonProperty("max_results")]
        public int? MaxResults
        {
            get
            {
                return this.maxResults;
            }

            set
            {
                this.shouldSerialize["max_results"] = true;
                this.maxResults = value;
            }
        }

        /// <summary>
        /// The search query.
        /// </summary>
        [JsonProperty("query", NullValueHandling = NullValueHandling.Ignore)]
        public string Query { get; set; }

        /// <summary>
        /// Restricts the results to one vertical or data set.
        /// Currently available: "news", "wikipedia", "people", "companies".
        /// When omitted, the default scope is searched. A scope that does not exist,
        /// or that this key cannot reach, returns 404.
        /// </summary>
        [JsonProperty("scope")]
        public string Scope
        {
            get
            {
                return this.scope;
            }

            set
            {
                this.shouldSerialize["scope"] = true;
                this.scope = value;
            }
        }

        /// <summary>
        /// How much work goes into ordering the results. It does not change which
        /// corpus is searched -- that is `scope` -- so any scope can be requested in
        /// either tier.
        /// `"base"` returns first-stage ranking. `"pro"` adds a ranking stage for
        /// higher precision at the top of the list.
        /// Unset resolves to `"pro"`, so `"base"` is opt-out. A scope with no Pro
        /// configuration serves `"pro"` exactly as `"base"` rather than failing, so a
        /// caller may always ask for `"pro"`.
        /// The name is matched without regard to case, and surrounding whitespace is
        /// ignored, so "pro", "PRO" and " Pro " are one tier. A name that is neither
        /// is rejected rather than defaulted, because the value selects a price.
        /// </summary>
        [JsonProperty("tier")]
        public string Tier
        {
            get
            {
                return this.tier;
            }

            set
            {
                this.shouldSerialize["tier"] = true;
                this.tier = value;
            }
        }

        /// <summary>
        /// Only include results published on or before this point. UTC throughout.
        /// A date, a datetime, or an offset from "now", in the same spellings
        /// from_date takes. A date written without a time covers the whole of that
        /// day, ending at 23:59:59.999; an offset is an instant.
        /// </summary>
        [JsonProperty("to_date")]
        public string ToDate
        {
            get
            {
                return this.toDate;
            }

            set
            {
                this.shouldSerialize["to_date"] = true;
                this.toDate = value;
            }
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"SearchRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetApiKey()
        {
            this.shouldSerialize["api_key"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetFields()
        {
            this.shouldSerialize["fields"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetFromDate()
        {
            this.shouldSerialize["from_date"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetMaxResults()
        {
            this.shouldSerialize["max_results"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetScope()
        {
            this.shouldSerialize["scope"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetTier()
        {
            this.shouldSerialize["tier"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetToDate()
        {
            this.shouldSerialize["to_date"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeApiKey()
        {
            return this.shouldSerialize["api_key"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeFields()
        {
            return this.shouldSerialize["fields"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeFromDate()
        {
            return this.shouldSerialize["from_date"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeMaxResults()
        {
            return this.shouldSerialize["max_results"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeScope()
        {
            return this.shouldSerialize["scope"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeTier()
        {
            return this.shouldSerialize["tier"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeToDate()
        {
            return this.shouldSerialize["to_date"];
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"ApiKey = {this.ApiKey ?? "null"}");
            toStringOutput.Add($"ExcludeDomains = {(this.ExcludeDomains == null ? "null" : $"[{string.Join(", ", this.ExcludeDomains)} ]")}");
            toStringOutput.Add($"Fields = {(this.Fields == null ? "null" : this.Fields.ToString())}");
            toStringOutput.Add($"FromDate = {this.FromDate ?? "null"}");
            toStringOutput.Add($"IncludeDomains = {(this.IncludeDomains == null ? "null" : $"[{string.Join(", ", this.IncludeDomains)} ]")}");
            toStringOutput.Add($"MaxResults = {(this.MaxResults == null ? "null" : this.MaxResults.ToString())}");
            toStringOutput.Add($"Query = {this.Query ?? "null"}");
            toStringOutput.Add($"Scope = {this.Scope ?? "null"}");
            toStringOutput.Add($"Tier = {this.Tier ?? "null"}");
            toStringOutput.Add($"ToDate = {this.ToDate ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}