// <copyright file="SnippetOptions.cs" company="APIMatic">
// SeltzApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SeltzApi.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SeltzApi.Standard.Models
{
    /// <summary>
    /// SnippetOptions.
    /// </summary>
    public class SnippetOptions
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private int? maxSnippets;
        private int? maxSnippetsPerResult;
        private int? maxTokens;
        private int? maxTokensPerResult;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "max_snippets", false },
            { "max_snippets_per_result", false },
            { "max_tokens", false },
            { "max_tokens_per_result", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="SnippetOptions"/> class.
        /// </summary>
        public SnippetOptions()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SnippetOptions"/> class.
        /// </summary>
        /// <param name="maxSnippets">max_snippets.</param>
        /// <param name="maxSnippetsPerResult">max_snippets_per_result.</param>
        /// <param name="maxTokens">max_tokens.</param>
        /// <param name="maxTokensPerResult">max_tokens_per_result.</param>
        public SnippetOptions(
            int? maxSnippets = null,
            int? maxSnippetsPerResult = null,
            int? maxTokens = null,
            int? maxTokensPerResult = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();

            if (maxSnippets != null)
            {
                this.MaxSnippets = maxSnippets;
            }

            if (maxSnippetsPerResult != null)
            {
                this.MaxSnippetsPerResult = maxSnippetsPerResult;
            }

            if (maxTokens != null)
            {
                this.MaxTokens = maxTokens;
            }

            if (maxTokensPerResult != null)
            {
                this.MaxTokensPerResult = maxTokensPerResult;
            }
        }

        /// <summary>
        /// Maximum snippets returned across all documents. Accepted range 1-512.
        /// No default. Left unset, no response-wide ceiling applies at all, which is the
        /// recommended setting: `max_snippets_per_result` already bounds every document, so the
        /// response is bounded without one.
        /// This budget is spent one snippet per document at a time, so every document gets its best
        /// snippet before any document gets a second. This value is potentially raised to ensure each
        /// document can be given at least one snippet.
        /// </summary>
        [JsonProperty("max_snippets")]
        public int? MaxSnippets
        {
            get
            {
                return this.maxSnippets;
            }

            set
            {
                this.shouldSerialize["max_snippets"] = true;
                this.maxSnippets = value;
            }
        }

        /// <summary>
        /// Maximum snippets from any single document.
        /// Defaults to 16, accepted range 1-256.
        /// </summary>
        [JsonProperty("max_snippets_per_result")]
        public int? MaxSnippetsPerResult
        {
            get
            {
                return this.maxSnippetsPerResult;
            }

            set
            {
                this.shouldSerialize["max_snippets_per_result"] = true;
                this.maxSnippetsPerResult = value;
            }
        }

        /// <summary>
        /// Ceiling on tokens across all snippets in the response.
        /// Defaults to 8192, accepted range 512-65536.
        /// Spent in the same order as `max_snippets`, one snippet per document at a time, but unlike
        /// `max_snippets` this ceiling is not raised to fit `max_results`. Set it low against many
        /// results and the budget runs out partway through a round: the documents it does not reach
        /// are still returned, with no snippets at all. If every result needs a snippet, raise this
        /// or lower `max_results`.
        /// </summary>
        [JsonProperty("max_tokens")]
        public int? MaxTokens
        {
            get
            {
                return this.maxTokens;
            }

            set
            {
                this.shouldSerialize["max_tokens"] = true;
                this.maxTokens = value;
            }
        }

        /// <summary>
        /// Ceiling on tokens of snippets from any single document.
        /// Defaults to 4096, accepted range 128-32768.
        /// </summary>
        [JsonProperty("max_tokens_per_result")]
        public int? MaxTokensPerResult
        {
            get
            {
                return this.maxTokensPerResult;
            }

            set
            {
                this.shouldSerialize["max_tokens_per_result"] = true;
                this.maxTokensPerResult = value;
            }
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"SnippetOptions : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetMaxSnippets()
        {
            this.shouldSerialize["max_snippets"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetMaxSnippetsPerResult()
        {
            this.shouldSerialize["max_snippets_per_result"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetMaxTokens()
        {
            this.shouldSerialize["max_tokens"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetMaxTokensPerResult()
        {
            this.shouldSerialize["max_tokens_per_result"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeMaxSnippets()
        {
            return this.shouldSerialize["max_snippets"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeMaxSnippetsPerResult()
        {
            return this.shouldSerialize["max_snippets_per_result"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeMaxTokens()
        {
            return this.shouldSerialize["max_tokens"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeMaxTokensPerResult()
        {
            return this.shouldSerialize["max_tokens_per_result"];
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"MaxSnippets = {(this.MaxSnippets == null ? "null" : this.MaxSnippets.ToString())}");
            toStringOutput.Add($"MaxSnippetsPerResult = {(this.MaxSnippetsPerResult == null ? "null" : this.MaxSnippetsPerResult.ToString())}");
            toStringOutput.Add($"MaxTokens = {(this.MaxTokens == null ? "null" : this.MaxTokens.ToString())}");
            toStringOutput.Add($"MaxTokensPerResult = {(this.MaxTokensPerResult == null ? "null" : this.MaxTokensPerResult.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}